version: '3.2'

services:
  proxy:
    build: ./src
    image: mproxy
    container_name: mproxy
    command: bash -c "./run.sh"
    volumes:
      - type: bind
        source: ./var
        target: /var/log/erss
    ports:
      - "12345:12345"